<?php
namespace legoboy\blockchanger;
use pocketmine\block\Block;
use pocketmine\plugin\PluginBase;
use pocketmine\level\Position;
use pocketmine\utils\Config;
class Main extends PluginBase{
  public function onEnable(){
  	$this->saveDefaultConfig();
    $this->getServer()->getScheduler()->scheduleDelayedRepeatingTask(new ChangeBlockTask($this, new Position($this->getConfig()->get("x1"), $this->getConfig()->get("y1"), $this->getConfig()->get("z1"), $this->getServer()->getDefaultLevel()), [Block::get(Block::GOLD_BLOCK, 0), Block::get(Block::IRON_BLOCK, 15)]), $this->getConfig()->get("ticks"), $this->getConfig()->get("ticks"));
    $this->getServer()->getScheduler()->scheduleDelayedRepeatingTask(new ChangeBlockTask($this, new Position($this->getConfig()->get("x2"), $this->getConfig()->get("y2"), $this->getConfig()->get("z2"), $this->getServer()->getDefaultLevel()), [Block::get(Block::GOLD_BLOCK, 0), Block::get(Block::IRON_BLOCK, 15)]), $this->getConfig()->get("ticks"), $this->getConfig()->get("ticks"));
    $this->getServer()->getScheduler()->scheduleDelayedRepeatingTask(new ChangeBlockTask($this, new Position($this->getConfig()->get("x3"), $this->getConfig()->get("y3"), $this->getConfig()->get("z3"), $this->getServer()->getDefaultLevel()), [Block::get(Block::GOLD_BLOCK, 0), Block::get(Block::IRON_BLOCK, 15)]), $this->getConfig()->get("ticks"), $this->getConfig()->get("ticks"));
    $this->getServer()->getScheduler()->scheduleDelayedRepeatingTask(new ChangeBlockTask($this, new Position($this->getConfig()->get("x4"), $this->getConfig()->get("y4"), $this->getConfig()->get("z4"), $this->getServer()->getDefaultLevel()), [Block::get(Block::GOLD_BLOCK, 0), Block::get(Block::IRON_BLOCK, 15)]), $this->getConfig()->get("ticks"), $this->getConfig()->get("ticks"));
    $this->getServer()->getScheduler()->scheduleDelayedRepeatingTask(new ChangeBlockTask($this, new Position($this->getConfig()->get("x5"), $this->getConfig()->get("y5"), $this->getConfig()->get("z5"), $this->getServer()->getDefaultLevel()), [Block::get(Block::GOLD_BLOCK, 0), Block::get(Block::IRON_BLOCK, 15)]), $this->getConfig()->get("ticks"), $this->getConfig()->get("ticks"));
    $this->getServer()->getScheduler()->scheduleDelayedRepeatingTask(new ChangeBlockTask($this, new Position($this->getConfig()->get("x6"), $this->getConfig()->get("y6"), $this->getConfig()->get("z6"), $this->getServer()->getDefaultLevel()), [Block::get(Block::GOLD_BLOCK, 0), Block::get(Block::IRON_BLOCK, 15)]), $this->getConfig()->get("ticks"), $this->getConfig()->get("ticks"));
    $this->getServer()->getScheduler()->scheduleDelayedRepeatingTask(new ChangeBlockTask($this, new Position($this->getConfig()->get("x7"), $this->getConfig()->get("y7"), $this->getConfig()->get("z7"), $this->getServer()->getDefaultLevel()), [Block::get(Block::GOLD_BLOCK, 0), Block::get(Block::IRON_BLOCK, 15)]), $this->getConfig()->get("ticks"), $this->getConfig()->get("ticks"));
    $this->getServer()->getScheduler()->scheduleDelayedRepeatingTask(new ChangeBlockTask($this, new Position($this->getConfig()->get("x8"), $this->getConfig()->get("y8"), $this->getConfig()->get("z8"), $this->getServer()->getDefaultLevel()), [Block::get(Block::GOLD_BLOCK, 0), Block::get(Block::IRON_BLOCK, 15)]), $this->getConfig()->get("ticks"), $this->getConfig()->get("ticks"));
    $this->getServer()->getScheduler()->scheduleDelayedRepeatingTask(new ChangeBlockTask($this, new Position($this->getConfig()->get("x9"), $this->getConfig()->get("y9"), $this->getConfig()->get("z9"), $this->getServer()->getDefaultLevel()), [Block::get(Block::GOLD_BLOCK, 0), Block::get(Block::IRON_BLOCK, 15)]), $this->getConfig()->get("ticks"), $this->getConfig()->get("ticks"));
    $this->getServer()->getScheduler()->scheduleDelayedRepeatingTask(new ChangeBlockTask($this, new Position($this->getConfig()->get("x10"), $this->getConfig()->get("y10"), $this->getConfig()->get("z10"), $this->getServer()->getDefaultLevel()), [Block::get(Block::GOLD_BLOCK, 0), Block::get(Block::IRON_BLOCK, 15)]), $this->getConfig()->get("ticks"), $this->getConfig()->get("ticks"));
    $this->getServer()->getScheduler()->scheduleDelayedRepeatingTask(new ChangeBlockTask($this, new Position($this->getConfig()->get("x11"), $this->getConfig()->get("y11"), $this->getConfig()->get("z11"), $this->getServer()->getDefaultLevel()), [Block::get(Block::GOLD_BLOCK, 0), Block::get(Block::IRON_BLOCK, 15)]), $this->getConfig()->get("ticks"), $this->getConfig()->get("ticks"));
    $this->getServer()->getScheduler()->scheduleDelayedRepeatingTask(new ChangeBlockTask($this, new Position($this->getConfig()->get("x12"), $this->getConfig()->get("y12"), $this->getConfig()->get("z12"), $this->getServer()->getDefaultLevel()), [Block::get(Block::GOLD_BLOCK, 0), Block::get(Block::IRON_BLOCK, 15)]), $this->getConfig()->get("ticks"), $this->getConfig()->get("ticks"));
  }
}
